### ISSUE TITLE
New front functionnality : Translation

### ISSUE THREAD

**Issue by HugoLAMOUREUX** [HugoLAMOUREUX/Spotidata#36]
### Summary

Allow the user to switch to another language (french, english and spanish for now)

### Basic Example

When another language is selected, all the text displayed is translated to the other language

### Drawbacks

French, spanish and english speaker will be able to use our app

**Comment by CorkyDork** [comment]
Hey, I can add a Russian translation if you open an issue.

**Comment by HugoLAMOUREUX** [comment]
I have open an issue for the russian translation !
