### ISSUE TITLE
Documentation : Spanish readme translation

### ISSUE THREAD

**Issue by HugoLAMOUREUX** [HugoLAMOUREUX/Spotidata#38]
### Summary

Create a file README_es.md and translate the README.md in spanish in this file

### Basic Example

A new file README_es.md should be added and should be the same as the original README.md but in spanish

### Drawbacks

allow the spanish speakers to understand our app

**Comment by Tanmay-Joshi73** [comment]
Hello, I would like to contribute. Would you be able to assign me a task?

**Comment by Tanmay-Joshi73** [comment]
Would it be possible for you to assign me this project?

**Comment by HugoLAMOUREUX** [comment]
Yes I've assigned you this issues !
