### ISSUE TITLE
🐛 [BUG] - Bug fixed: App.jsx "import Tops failed"

### ISSUE THREAD

**Issue by AlexLunaP** [HugoLAMOUREUX/Spotidata#43]
### Description

It seems the error happens because the file App.jsx tries to import "./pages/tops" but that file was called "./pages/Tops".

Just adding this issue to share this bug. I've created a pull request that fixes it.
I just changed the line 9 in "src/App.jsx" file to:
import Tops from "./pages/Tops"; and the error was fixed.

Note: My system has Ubuntu 22.04 LTS and Node v18.16.0

### Reproduction URL

https://github.com/AlexLunaP/Spotidata

### Reproduction steps

```bash
1. Launch the front
2. The error pops up in the web browser
```

### Screenshots

![Screenshot from 2023-04-25 17-40-48](https://user-images.githubusercontent.com/61513467/234352656-f2258ff4-1502-4e12-bfb9-b89a79376cc1.png)

![Screenshot from 2023-04-25 17-41-22](https://user-images.githubusercontent.com/61513467/234352672-e6604aea-05f3-45b8-b1be-58e22db1948d.png)

### Browsers

Chrome

### OS

Linux

**Comment by HugoLAMOUREUX** [comment]
Indeed, it was not causing any problem on Windows for me but maybe it's different on linux this is weird. Thank you for fixing this bug !

**Comment by AlexLunaP** [comment]
Yep, seems to be something related to Linux :)
