### ISSUE TITLE
New frontend functionnality : Russian translation

### ISSUE THREAD

**Issue by HugoLAMOUREUX** [HugoLAMOUREUX/Spotidata#49]
### Summary

The goal is to add a russian translation.
Open the file "/front/src/i18n.jsx" and in the json object you can change what's under ru :
You'll have to translate the sentences from english to russian.
You'll simply need to modify the strings and put them in russian instead of english.
I'll add a button later on to select the russian language

### Basic Example

ru: {
translation: {
login: "Login with Spotify",

become :
ru: {
translation: {
login: "Войти через Spotify",

(maybe the translation isn't correct)

### Drawbacks

allow the russian people to use our app

**Comment by CorkyDork** [comment]
Will do this

**Comment by CorkyDork** [comment]
Hey, I made a translation but when I am trying to push, it says I don't have written permission. Should you grant me permission or how does it work?

**Comment by CorkyDork** [comment]
Never mind, I think I figured it out. I had to fork it and then push. Can you see it?

**Comment by HugoLAMOUREUX** [comment]
Yes everything is good ! Thank you for your contribution !
