### ISSUE TITLE
New backend functionnality : getAlbumTracks() 

### ISSUE THREAD

**Issue by SharkyFlou** [HugoLAMOUREUX/Spotidata#7]
### Summary

Get a list of all the tracks contained in an album, with their id, name, artist, cover and number of tracks.
More info there :
https://github.com/thelinmichael/spotify-web-api-node
spotifyApi.getAlbumTracks('41MnTivkwTO3UUJ8DrqEJJ', { limit : 5, offset : 1 })
  .then(function(data) {
    console.log(data.body);
  }, function(err) {
    console.log('Something went wrong!', err);
  });

### Basic Example

Would be called like that :
`getAlbumTracks(req, res){...}`
Return a JSON with everything.

### Drawbacks

Allows you te see all the tracks in an album.

**Comment by alvarohghg** [comment]
Hello, could I work on this issue?

**Comment by SharkyFlou** [comment]
Yes, no problem

**Comment by alvarohghg** [comment]
Hi again, I'm a bit lost. Where do I have to write the required function? Do I need to use the existing controllers or do I need to create another one new apart from playListController and trackController?

**Comment by alvarohghg** [comment]
Hi, thank you for the info, this is my email: lvaro.berjillos@gmail.com (yes, it has no "a" at the beginning, not a typo)

**Comment by HugoLAMOUREUX** [comment]
Okay everything should be fine now, if you ask any questions don't hesitate to ask
